### ISSUE TITLE
Imgui vec2

### ISSUE THREAD

**Issue by elect86** [vfmachado/br.fritzen.engine#1]
Hi, 

I answer here because github issue replying seems to experience problems: I answer that, then if I refresh I don't see my reply anymore, but if I reply once again, then I see all the previos replies.

I also tried to modify your comment, maybe it was messing it up because of the images, it worked for a refresh, then back to none comments of mine. Then if I modify your comment again, it complains there was another edit in the meanwhile..

A mess..

Anyway, this is my original reply

"
Hi,

yeah, Vec2 is the most common class in the project (you can see it also here)

    There is a solution for this behavior? Thank you

The solution would be to switch all the classes to float fields, and change consequently all the function signatures, class properties and the code using those classes, also giving up on operator overloading and making code much more verbose, less similar to the original C++ and more error prone.

I never experienced problems with that, even on old laptops from 7/8 years.

But if it's a problem on your machine, if you want you may want to give a try and change all of that and see if you get any benefit in term of performances.

You could take care of a branch for that
"

**Comment by vfmachado** [comment]
Thanks for reply.
